os: linux
language: python
sudo: required
dist: bionic
group: edge
cache:
  pip: true
python:
- 3.6
- 3.7
- 3.8
before_install:
- apt-get update -qq
- apt-get install -yqq python3-pip
- pip3 install pytest codecov pytest-cov
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest -v --cov=attackerkb_api
after_success:
- python setup.py sdist
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: Kn1hERxacUEUwD4J3SAqW1Bpc5A39i+ArE+0QVMBffxeEWe7nM26aYlYpwm4nE6/TX1mPyCCsCcljTjXuENOduoU6Hq0C3dQEdgQfgkjKSR55tM0D+Yircz5W/YMKks9h5O2fP6h0OPFqAGU3wngMLX6k1UIe5VFB+Z+/O7uTNjq1/cf8bukunb13r1M0ARRjdA47HcsIxkCCwpS7oi9WhxW0M5dg7ZTfSBzCUYaa0cumCdKlXVyBqH6yOx04iFGe8Z25ixJ2lKCOK9f9jy/sIW1fMlnM//PClN8DDVFRuIFP17elz9/Uc2MIxX72hoKq7GlI45GOG/D/setKfrZVQ7N9vnxs9P/S1r3AGcQ3yH2uofT3Z+nEIabsgEwPvbqeNffgmGTjRNK6oLqTzFJUIWwO7E+Bhv5W37DOGxGIO2EHj/uXkhohhNZj9COsevZQUWk5s+Qg8RD0tCPfjlWqcTw0WZKuTaIHdfHbA8jOvEvHviXylf7U7n1oRdrSwjTqcBhI87aCQoZrpcmF3DDuK6ozJT0qhHHYWXQXMjbvbqIghzwuie6QSD5dDJA0HQ7GP2T6Mr4dt0yEL+m0ukO3I4o3iS3UoZkziUVOghX/if6hbpT8cEWNtIPvRQEInf6eRBLR/UP1HLwwWPztLwcisk0tX0Oi5EIly2dJM1jWb8=
  on:
    tags: true
  skip_existing: true
env:
  global:
    secure: RZ9NU+WTpUWcsfGwz7qT9i5cdJ3I9EWNH3OFPdZ47sy2fiBs76X+xXtyoeAJOgqMoXPs7q0Gi7dnNLKkjFqVTIZq3CNf1TEoupUj/tIvKublF82tJ/pKJGqNM2b378cNJzj9pwVdtAM5Et56Aev/PX33RDyiPtcm5Hy6rhnNcwVzgJ1T29vwlJvAEVAsz3ZxNAItrNz2i6PmK/CD7AyoAd3HfCzQmFYJfilmEuY7jvjVQ7QhFoB4tmyTEM5O1bVghOSaVTFNgtq+XNZzuffxrX7/nqunVQP3S0QjuHLx9fkB7Sh1hQTUMP8AXzDZbuLsnP8hZcMhDn1dvgrWZLi28y3AptvLNmGYryNY0DB8L7Q3MxwiGSHkXQyUdAlvApjk7J5z1vmiGlMF7flP2X+Bu0J9Tq+sXsmvrOBT3MIF8WGeNZtJ4ceecBA74rxyDyurWmzfjK73z+JVK5VBd09zW2uy9uDGRuKzJy9ba5qtHltv6Wq1dJ4p2T5EH4eU/Ebq14WL3+gJSKn9ApH9CE2t9Ow5Y0C/W5VHc3p/65cVFLVCq+BBYEo4cxRUOFoTEqNvGESfz4gl/MlkeLDCV6/i9/BW5KKV1nCfeVUW8fVQ5gUX3nl7ZMNqgLyHa/Eb/OVX6LpWbYIVDVZw7o4rnad7F2PwU8S5eHVzBHF+cuvaZcI=
